# Generated by Django 4.0.4 on 2022-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('To-Do', 'To-Do'), ('Doing', 'Doing'), ('Need Checking', 'Need Checking'), ('Done', 'Done')], max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
