# Generated by Django 4.0.4 on 2022-05-15 19:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collabapp', '0005_alter_collaborator_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaborator',
            new_name='Profile',
        ),
    ]
