# Generated by Django 4.0.4 on 2022-05-18 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0008_remove_profile_email_alter_profile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='collabapp.project'),
        ),
    ]
