# Generated by Django 4.0.4 on 2022-05-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0010_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
