# Generated by Django 4.0.4 on 2022-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0011_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='task_members', to='collabapp.task'),
        ),
    ]
