# Generated by Django 4.0.4 on 2022-05-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0012_profile_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
