# Generated by Django 4.0.4 on 2022-05-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0015_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/default_pfp.png', null=True, upload_to=''),
        ),
    ]
